version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brainbytes-frontend
    command: npm run dev
    ports:
      - "8080:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    dns:
      - 8.8.8.8
      - 1.1.1.1


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainbytes-backend
    command: npm start
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/brainbytes_test
      - JWT_SECRET=brainbytes-local-secret
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    depends_on:
      - mongo
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./backend:/app
      - /app/node_modules


  mongo:
    image: mongo:4.4
    container_name: brainbytes-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: