name: Auto Generate Commit Sheet

on:
  push:
    branches:  main 


jobs:
  commits-to-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history so git shortlog counts all commits
          token: ${{ secrets.MY_PAT_TOKEN }}

      - name: Export all commits to CSV
        run: |
          echo "Commit Hash, Author, Date, Commit Message" > commits.csv
          git log --pretty=format:'"%h,%an,%ad,%s"' --date=format:"%Y-%m-%d %H:%M:%S" >> commits.csv


      - name: Commit CSV and push the spreadsheet file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'commits.csv'
          default_author: github_actions
          message: 'chore: rewrite full commit tracking workflow [skip ci]'
        
