name: Auto Generate Commit Sheet

on:
  push:
    branches:  main 


jobs:
  commits-to-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history so git shortlog counts all commits

      - name: Calculate commit numbers and create CSV sheet
        run: |
          TOTAL_COMMITS=$(git rev-list --count HEAD)

          LATEST_HASH=$(git log -1 --format="%h")
          LATEST_MSG=$(git log -1 --format="%s")
          LATEST_AUTHOR=$(git log -1 --format="%an")
          LATEST_DATE=$(git log -1 --format="%cd")

          if [ ! -f commits.csv ]; then
            echo "Timestamp","Total Commits","Latest Hash","Latest Message","Latest Author","Latest Date" > commits.csv
          fi

          echo "$TIMESTAMP, $TOTAL_COMMITS, $LATEST_HASH, \"$LATEST_MSG\", \"$LATEST_AUTHOR\", \"$LATEST_DATE\"" >> commits.csv

      - name: Commit CSV and push the spreadsheet filw
        uses: EndBug/add-and-commit@v9
        with:
          add: 'commits.csv'
          default_author: github_actions
          message: 'chore: Auto update commit spreadsheet [skip ci]'
        
